# Generated by Django 3.0.8 on 2020-07-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('left', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_set', to='tree.Node')),
                ('right', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_set', to='tree.Node')),
            ],
        ),
    ]
